FROM ruby:3.2.2-alpine

RUN apk add --update --no-cache \
    bash=5.2.21-r0 \
    build-base=0.5-r3 \
    nodejs=20.10.0-r1

WORKDIR /app

COPY Gemfile Gemfile.lock ./

RUN gem install bundler --no-document --conservative --version 2.4.19

# Install all dependencies
RUN bundle config --local with development && \
    bundle install --jobs=3 --retry=3

COPY . ./
