FROM ruby:3.4.6-alpine

RUN apk add --update --no-cache \
    bash=5.2.26-r0 \
    build-base=0.5-r3 \
    nodejs=20.13.1-r0

WORKDIR /app

COPY Gemfile Gemfile.lock ./

# Install all dependencies
RUN bundle config --local with development && \
    bundle install --jobs=3 --retry=3

COPY . ./
