# fly.toml app configuration file generated for rouge-dingus on 2023-09-06T10:42:18+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rouge-dingus"
primary_region = "sin"

[build]

[http_service]
  internal_port = 9292
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
